// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xfxinsjvyvsdjgudhrnz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhmeGluc2p2eXZzZGpndWRocm56Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgzNjY4NTgsImV4cCI6MjA3Mzk0Mjg1OH0.V0aF0oB7jI83N_lBHpelYA0Zd-9T2g5h60UC1VN7OqE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});